### ISSUE TITLE
Telemetry from ASP.NET app not flowing if ApplicationInsights.config in the root is updated

### ISSUE THREAD

**Issue by AlexBulankou** [AlexBulankou/ai-talk1#24]
@SergeyKanzhelev, ApplicationInsights.config is read from bin dir, right? For some reason I'm not seeing any telemetry until I change it in the root dir. Until I do this, all telemetry is unconfigured (as I can see in debugger) and Metrics stream is not showing anything.

**Comment by AlexBulankou** [comment]
Just confirmed again this is the case. I'll propose update to instructions as part of my PR to update ikey in the root, not just in the bin folder

**Comment by SergeyKanzhelev** [comment]
Oh, it is this problem: http://apmtips.com/blog/2014/12/23/applicationinsights-dot-config-file-search-order/ I'm curious why the root config is read first
