### ISSUE TITLE
Do we need HTTPS on apps? It shows cert error in Edge

### ISSUE THREAD

**Issue by SergeyKanzhelev** [AlexBulankou/ai-talk1#3]
Let's not confuse people with this error and use plain http (if possible):

![image](https://cloud.githubusercontent.com/assets/9950081/21068528/6c56be9c-be27-11e6-8a44-2fd77342b57c.png)

**Comment by AlexBulankou** [comment]
Hmm. Couldn't repro so far. Let me try on the VM that I'm preparing

**Comment by SergeyKanzhelev** [comment]
It is even worse for me - when I run from VS everything works. When run from IIS - I'm getting: 

```
{"The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."}
```

when ASP.NET calls into node.js

![image](https://cloud.githubusercontent.com/assets/9950081/21089630/a0a42afe-bfee-11e6-8790-41c4e31ccb27.png)

**Comment by SergeyKanzhelev** [comment]
https://github.com/AlexBulankou/ai-talk1/pull/6
