### ISSUE TITLE
Ex5: operation_id is not recorded in requests

### ISSUE THREAD

**Issue by AlexBulankou** [AlexBulankou/ai-talk1#30]
Going through exercise 5, I don't see operatio_id or source fields populated in requests. This is with or without telemetry initializer. @SergeyKanzhelev, can you send me your node.JS app you were using?

**Comment by SergeyKanzhelev** [comment]
I just followed instructions step by step. `Source` and `operation_id` fields will not be set if ASP.NET app didn't send headers (meaning you do not have Status Monitor enabled). So just enable it.
