### ISSUE TITLE
No perf counters collected for ASP.NET application

### ISSUE THREAD

**Issue by SergeyKanzhelev** [AlexBulankou/ai-talk1#33]
@AlexBulankou do you see perf counters collected for ASP.NET app?

**Comment by SergeyKanzhelev** [comment]
Turns out to be permissions issue:

![image](https://cloud.githubusercontent.com/assets/9950081/22229132/9a2380b8-e18a-11e6-8753-9121fc2ce171.png)

**Comment by SergeyKanzhelev** [comment]
@AlexBulankou if we will update computer - need to fix it

**Comment by AlexBulankou** [comment]
No, I didn't

**Comment by AlexBulankou** [comment]
@SergeyKanzhelev perhaps we should request the change to VM after making our default admin user AppPoolIdentify. This addressed the problem, perf counters start flowing.

**Comment by SergeyKanzhelev** [comment]
My biggest worry with VM is it scheduled for updates. When I copied it and started - it spent 15 minutes "configuring updates" before shown the login window. Do you know is there a way to test VM as it set up in the lab?

**Comment by AlexBulankou** [comment]
cleaning up

**Comment by AlexBulankou** [comment]
cleaning up

**Comment by AlexBulankou** [comment]
cleaning up
